package dip;

/*
 * HIGH-LEVEL MODULES SHOULD NOT DEPEND ON LOW-LEVEL MODULES. BOTH SHOULD DEPEND ON ABSTRACTIONS.
 * ABSTRACTIONS SHOULD NOT DEPENDE ON DETAILS. DETAILS SHOULD DEPENDE ON ABSTRACTIONS.
 */

public class DependencyInversionPrinciple 
{
	
}
